server:
  port: 8080
spring:
  application:
    name: spring-video-streaming
  datasource:
    username: ${spring.video.streaming.datasource.username}
    url: ${spring.video.streaming.datasource.url}
    password: ${spring.video.streaming.datasource.password}
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  config:
    import: "optional:configserver:"
  cloud:
    config:
      label: latest
      profile: local
      uri: http://localhost:8763
      username: admin
      password: password
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
logging:
  level:
    com:
      acarreno:
        poc: ${spring.video.streaming.logging.level}
    org:
      springframework:
        ws: ${org.springframework.ws.logging.level}
cloudinary:
  name: ${spring.video.streaming.cloudinary.name}
  api_key: ${spring.video.streaming.cloudinary.api_key}
  api_secret: ${spring.video.streaming.cloudinary.api_secret}
