server:
  port: 8080
spring:
  application:
    name: spring-video-streaming
  datasource:
    username: admin
    url: jdbc:postgresql://localhost:5432/test_project
    password: Test123*
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
logging:
  level:
    com:
      acarreno:
        poc: DEBUG
    org:
      springframework:
        ws: DEBUG
