version: "3.8"
name: postgres
services:
  postgres:
    image: postgres:latest
    hostname: server
    container_name: postgres-server
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Test123*
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql
    networks:
      - postgres-net
volumes:
  postgres-data:
networks:
  postgres-net:
